[package]
name = "builder"
version = "0.1.0"
authors = ["niqitosiq <nikitashtanko@yahoo.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84" 
getrandom = { version = "0.2", features = ["js"] }
log = "0.4.6"
wasm-logger = "0.2.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
swc_core = "0.92.10"
swc_ecma_parser = "0.144.2"
swc_ecma_codegen = "0.149.2"
swc_ecma_transforms = "0.230.1"
serde_json = "1.0.117"
serde = "1.0.203"
swc_ecma_ast = "0.113.6"
swc_common = "0.33.26"
swc_atoms = "0.6.7"
swc_ecma_transforms_base = "0.138.3"
swc_ecma_transforms_typescript = "0.189.1"
swc_ecma_visit = "0.99.1"
swc_ecma_transforms_proposal = "0.172.3"
swc_ecma_transforms_react = "0.184.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
